// Generated by gencpp from file tutorial_srvs/TutorialSrvRequest.msg
// DO NOT EDIT!


#ifndef TUTORIAL_SRVS_MESSAGE_TUTORIALSRVREQUEST_H
#define TUTORIAL_SRVS_MESSAGE_TUTORIALSRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tutorial_srvs
{
template <class ContainerAllocator>
struct TutorialSrvRequest_
{
  typedef TutorialSrvRequest_<ContainerAllocator> Type;

  TutorialSrvRequest_()
    : command()  {
    }
  TutorialSrvRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::tutorial_srvs::TutorialSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tutorial_srvs::TutorialSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TutorialSrvRequest_

typedef ::tutorial_srvs::TutorialSrvRequest_<std::allocator<void> > TutorialSrvRequest;

typedef boost::shared_ptr< ::tutorial_srvs::TutorialSrvRequest > TutorialSrvRequestPtr;
typedef boost::shared_ptr< ::tutorial_srvs::TutorialSrvRequest const> TutorialSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tutorial_srvs::TutorialSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tutorial_srvs::TutorialSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tutorial_srvs::TutorialSrvRequest_<ContainerAllocator1> & lhs, const ::tutorial_srvs::TutorialSrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tutorial_srvs::TutorialSrvRequest_<ContainerAllocator1> & lhs, const ::tutorial_srvs::TutorialSrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tutorial_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tutorial_srvs::TutorialSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial_srvs::TutorialSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial_srvs::TutorialSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial_srvs::TutorialSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial_srvs::TutorialSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial_srvs::TutorialSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tutorial_srvs::TutorialSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const ::tutorial_srvs::TutorialSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcba5e21e920a3a2bULL;
  static const uint64_t static_value2 = 0x7b375cb65b64cdeaULL;
};

template<class ContainerAllocator>
struct DataType< ::tutorial_srvs::TutorialSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tutorial_srvs/TutorialSrvRequest";
  }

  static const char* value(const ::tutorial_srvs::TutorialSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tutorial_srvs::TutorialSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string command\n"
;
  }

  static const char* value(const ::tutorial_srvs::TutorialSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tutorial_srvs::TutorialSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TutorialSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tutorial_srvs::TutorialSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tutorial_srvs::TutorialSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUTORIAL_SRVS_MESSAGE_TUTORIALSRVREQUEST_H
