// Generated by gencpp from file tutorial_srvs/TutorialSrvResponse.msg
// DO NOT EDIT!


#ifndef TUTORIAL_SRVS_MESSAGE_TUTORIALSRVRESPONSE_H
#define TUTORIAL_SRVS_MESSAGE_TUTORIALSRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tutorial_srvs
{
template <class ContainerAllocator>
struct TutorialSrvResponse_
{
  typedef TutorialSrvResponse_<ContainerAllocator> Type;

  TutorialSrvResponse_()
    : result()
    , message()  {
    }
  TutorialSrvResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _result_type;
  _result_type result;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::tutorial_srvs::TutorialSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tutorial_srvs::TutorialSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TutorialSrvResponse_

typedef ::tutorial_srvs::TutorialSrvResponse_<std::allocator<void> > TutorialSrvResponse;

typedef boost::shared_ptr< ::tutorial_srvs::TutorialSrvResponse > TutorialSrvResponsePtr;
typedef boost::shared_ptr< ::tutorial_srvs::TutorialSrvResponse const> TutorialSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tutorial_srvs::TutorialSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tutorial_srvs::TutorialSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tutorial_srvs::TutorialSrvResponse_<ContainerAllocator1> & lhs, const ::tutorial_srvs::TutorialSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tutorial_srvs::TutorialSrvResponse_<ContainerAllocator1> & lhs, const ::tutorial_srvs::TutorialSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tutorial_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tutorial_srvs::TutorialSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial_srvs::TutorialSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial_srvs::TutorialSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial_srvs::TutorialSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial_srvs::TutorialSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial_srvs::TutorialSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tutorial_srvs::TutorialSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b32ef3c4a478327333bfd0b603b07edb";
  }

  static const char* value(const ::tutorial_srvs::TutorialSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb32ef3c4a4783273ULL;
  static const uint64_t static_value2 = 0x33bfd0b603b07edbULL;
};

template<class ContainerAllocator>
struct DataType< ::tutorial_srvs::TutorialSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tutorial_srvs/TutorialSrvResponse";
  }

  static const char* value(const ::tutorial_srvs::TutorialSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tutorial_srvs::TutorialSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::tutorial_srvs::TutorialSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tutorial_srvs::TutorialSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TutorialSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tutorial_srvs::TutorialSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tutorial_srvs::TutorialSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.result);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUTORIAL_SRVS_MESSAGE_TUTORIALSRVRESPONSE_H
